language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t 4084685/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 4084685/docker-react npm run test -- --coverage